### ISSUE TITLE
DBSCAN usage problem

### ISSUE THREAD

**Issue by Alien-Empera** [flevet/PoCA#2]
Dear flevet,

  I want to use DBSCAN in the software to analyze membrane protein data, but I have encountered some problems.  

1. importing file

  What is the function of the "time" button when importing data? I find no 'time' information (except frame) in the example data.

2. parameters in DBSCAN analysis

  2.1 What's the difference between 'Min # locs' and 'Min # locs in cluster' on the upper right corner of the DBSCAN interface? 

  2.2 What is the function of the "cleaning" button? Is it used for multiblinking correction? How to use it?

3. visualization of clusters 

  3.1 I set 'Distance' and 'Min_locs' and got clusters. After creating objects I can double click to enlarge special object, but how to return to the whole view?

  **3.2** How can I analyse data with DBSCAN in the select ROI? First i clicked 'DBSCAN' without any selected ROI and got clusters. then I click 'circle 2D' and got a pink (selected) ROI. i click 'DBSCAN' again and nothing happened. If I select ROI first and then click 'DBSCAN', all the data instead of just the data in the ROI is being analyzed.
         
  I would be grateful if you could provide any help.

**Comment by flevet** [comment]
Hi,

1. The time would be the calibration time of your acquisition. So if you took a frame every 50 ms, you should put 50 in the "Time" textbox ans selection ms in the "Time unit". Currently, this is not used anywhere though.

2.1 "Min # locs" is the minimum number to classify a point as a core point (please refer to the original DBSCAN publication). "Min # locs in cluster" is an added variable in order to keep only clusters that have a number of localizations above this threshold.

2.2 This is indeed used to correct blinking in PALM datasets. This a a temporal grouping related to some statistics (please refer to the SR-Tesseler paper to have more information)

3.1 Use "the reset view button" (https://poca-smlm.github.io/images/poca_windows.png)

3.2 After verification, I don't think this is a feature currently available. I will add it when I have some time.

**Comment by Alien-Empera** [comment]
Thanks! 

By the way, what's the difference between 'size' and 'area' in DBSCAN result? What are the units of them? Is ‘area’ measured in nm2 and ‘size’ refered to diameter (if the imported data are in units of nm)?

**Comment by flevet** [comment]
Size is the average of the of the two (resp. three) axes of the ellipse (resp. ellipsoid) computed through principal component analysis of the objects' localizations.
You are right, the unit is the unit of the coordinates. If the coordinates are in nm, the area will be in nm²
